[build]
  publish = "dist/adea-solution-web/browser"
  command = "npm run build:static"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
